server:
  port: 8080

telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: search-service
    brokers:
      - port: 9092
        host: localhost
  consumer:
    groupId: search-consumer
    allowAutoTopicCreation: true

elasticsearch:
  auth:
    username: elastic
    password: elasticsearch
  nodes: http://localhost:9200