package fr.polyflix.search.infrastructure.repository.elasticsearch

import fr.polyflix.search.infrastructure.repository.elasticsearch.document.VideoDocument
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository

interface SpringElasticVideoRepository: ElasticsearchRepository<VideoDocument, String>