server:
  port: 8081

spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      video:
        topic: polyflix.video
        group-id: search-video-cg
      quiz:
        topic: polyflix.quiz
        group-id: search-quiz-cg
      user:
        topic: polyflix.user
        group-id: search-user-cg

seeders:
  enabled: false